/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhyRouteImport } from './routes/why'
import { Route as InstallDotshRouteImport } from './routes/install[.]sh'
import { Route as InstallDotps1RouteImport } from './routes/install[.]ps1'
import { Route as InstallRouteImport } from './routes/install'
import { Route as EvidenceRouteImport } from './routes/evidence'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as IndexRouteImport } from './routes/index'

const WhyRoute = WhyRouteImport.update({
  id: '/why',
  path: '/why',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallDotshRoute = InstallDotshRouteImport.update({
  id: '/install.sh',
  path: '/install.sh',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallDotps1Route = InstallDotps1RouteImport.update({
  id: '/install.ps1',
  path: '/install.ps1',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallRoute = InstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceRoute = EvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/evidence': typeof EvidenceRoute
  '/install': typeof InstallRoute
  '/install.ps1': typeof InstallDotps1Route
  '/install.sh': typeof InstallDotshRoute
  '/why': typeof WhyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/evidence': typeof EvidenceRoute
  '/install': typeof InstallRoute
  '/install.ps1': typeof InstallDotps1Route
  '/install.sh': typeof InstallDotshRoute
  '/why': typeof WhyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/evidence': typeof EvidenceRoute
  '/install': typeof InstallRoute
  '/install.ps1': typeof InstallDotps1Route
  '/install.sh': typeof InstallDotshRoute
  '/why': typeof WhyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/evidence'
    | '/install'
    | '/install.ps1'
    | '/install.sh'
    | '/why'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs'
    | '/evidence'
    | '/install'
    | '/install.ps1'
    | '/install.sh'
    | '/why'
  id:
    | '__root__'
    | '/'
    | '/docs'
    | '/evidence'
    | '/install'
    | '/install.ps1'
    | '/install.sh'
    | '/why'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRoute: typeof DocsRoute
  EvidenceRoute: typeof EvidenceRoute
  InstallRoute: typeof InstallRoute
  InstallDotps1Route: typeof InstallDotps1Route
  InstallDotshRoute: typeof InstallDotshRoute
  WhyRoute: typeof WhyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/why': {
      id: '/why'
      path: '/why'
      fullPath: '/why'
      preLoaderRoute: typeof WhyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/install.sh': {
      id: '/install.sh'
      path: '/install.sh'
      fullPath: '/install.sh'
      preLoaderRoute: typeof InstallDotshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/install.ps1': {
      id: '/install.ps1'
      path: '/install.ps1'
      fullPath: '/install.ps1'
      preLoaderRoute: typeof InstallDotps1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/install': {
      id: '/install'
      path: '/install'
      fullPath: '/install'
      preLoaderRoute: typeof InstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence': {
      id: '/evidence'
      path: '/evidence'
      fullPath: '/evidence'
      preLoaderRoute: typeof EvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRoute: DocsRoute,
  EvidenceRoute: EvidenceRoute,
  InstallRoute: InstallRoute,
  InstallDotps1Route: InstallDotps1Route,
  InstallDotshRoute: InstallDotshRoute,
  WhyRoute: WhyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
